"""Pre-populated demo data for TradeFlow Intelligence."""

from datetime import date, datetime

from app.models import (
    ComplianceItem,
    ComplianceStatus,
    Customer,
    CustomerType,
    Equipment,
    EquipmentStatus,
    Job,
    JobStatus,
    JobType,
    MaintenanceRecord,
    PricingRule,
    RevenueData,
    Technician,
)

# ---- Technicians ----

TECHNICIANS: list[Technician] = [
    Technician(
        id="tech-001",
        name="Carlos Mendez",
        skills=["plumbing", "general"],
        hourly_rate=85.0,
        availability="on_job",
        phone="(415) 555-0101",
        jobs_completed=142,
    ),
    Technician(
        id="tech-002",
        name="Sarah Chen",
        skills=["hvac", "electrical"],
        hourly_rate=95.0,
        availability="available",
        phone="(415) 555-0102",
        jobs_completed=198,
    ),
    Technician(
        id="tech-003",
        name="James O'Brien",
        skills=["electrical", "general"],
        hourly_rate=90.0,
        availability="available",
        phone="(415) 555-0103",
        jobs_completed=167,
    ),
    Technician(
        id="tech-004",
        name="Maria Santos",
        skills=["plumbing", "hvac"],
        hourly_rate=88.0,
        availability="on_job",
        phone="(415) 555-0104",
        jobs_completed=123,
    ),
    Technician(
        id="tech-005",
        name="David Park",
        skills=["hvac", "electrical", "general"],
        hourly_rate=100.0,
        availability="off_duty",
        phone="(415) 555-0105",
        jobs_completed=231,
    ),
]

# ---- Customers ----

CUSTOMERS: list[Customer] = [
    Customer(
        id="cust-001",
        name="Bay Area Homes LLC",
        type=CustomerType.residential,
        address="1450 Market St, San Francisco, CA 94102",
        phone="(415) 555-1001",
        email="contact@bayareahomes.com",
        total_spent=45200.00,
        job_count=18,
        last_service=date(2026, 3, 20),
        notes="Property management company, 12 residential units",
    ),
    Customer(
        id="cust-002",
        name="TechCorp Office Park",
        type=CustomerType.commercial,
        address="2800 Sand Hill Rd, Menlo Park, CA 94025",
        phone="(650) 555-2002",
        email="facilities@techcorp.com",
        total_spent=128500.00,
        job_count=32,
        last_service=date(2026, 3, 22),
        notes="Large campus, quarterly HVAC maintenance contract",
    ),
    Customer(
        id="cust-003",
        name="Sunset Senior Living",
        type=CustomerType.commercial,
        address="3200 Judah St, San Francisco, CA 94122",
        phone="(415) 555-3003",
        email="maintenance@sunsetsenior.org",
        total_spent=67800.00,
        job_count=24,
        last_service=date(2026, 3, 15),
        notes="Priority client, 24/7 emergency service agreement",
    ),
    Customer(
        id="cust-004",
        name="Pacific Heights Condos",
        type=CustomerType.residential,
        address="2400 Broadway, San Francisco, CA 94115",
        phone="(415) 555-4004",
        email="hoa@pacificheightscondos.com",
        total_spent=34600.00,
        job_count=14,
        last_service=date(2026, 3, 10),
        notes="HOA managed, 48-unit complex",
    ),
    Customer(
        id="cust-005",
        name="SF Unified School District",
        type=CustomerType.commercial,
        address="555 Franklin St, San Francisco, CA 94102",
        phone="(415) 555-5005",
        email="facilities@sfusd.edu",
        total_spent=198200.00,
        job_count=56,
        last_service=date(2026, 3, 24),
        notes="Government contract, multiple school locations",
    ),
    Customer(
        id="cust-006",
        name="Fremont Auto Mall",
        type=CustomerType.commercial,
        address="5700 Auto Mall Pkwy, Fremont, CA 94538",
        phone="(510) 555-6006",
        email="ops@fremontautomall.com",
        total_spent=52300.00,
        job_count=16,
        last_service=date(2026, 2, 28),
        notes="Multiple dealerships, mostly electrical and HVAC",
    ),
    Customer(
        id="cust-007",
        name="Oakland Children's Hospital",
        type=CustomerType.commercial,
        address="747 52nd St, Oakland, CA 94609",
        phone="(510) 555-7007",
        email="engineering@oakch.org",
        total_spent=215000.00,
        job_count=42,
        last_service=date(2026, 3, 25),
        notes="Critical facility, strict compliance requirements",
    ),
    Customer(
        id="cust-008",
        name="San Jose Convention Center",
        type=CustomerType.commercial,
        address="150 W San Carlos St, San Jose, CA 95113",
        phone="(408) 555-8008",
        email="events@sjcc.com",
        total_spent=87400.00,
        job_count=20,
        last_service=date(2026, 3, 18),
        notes="Large venue, seasonal demand spikes during events",
    ),
]

# ---- Jobs ----

JOBS: list[Job] = [
    Job(
        id="job-001",
        title="HVAC System Overhaul - Building A",
        customer_id="cust-002",
        customer_name="TechCorp Office Park",
        type=JobType.hvac,
        status=JobStatus.in_progress,
        technician_id="tech-002",
        technician_name="Sarah Chen",
        address="2800 Sand Hill Rd, Building A, Menlo Park, CA 94025",
        description="Complete HVAC system replacement for 3-story office building. Includes new rooftop units, ductwork modifications, and smart thermostat installation.",
        scheduled_date=date(2026, 3, 18),
        estimated_cost=45000.00,
        notes="Phase 1 of 3-phase project",
    ),
    Job(
        id="job-002",
        title="Emergency Pipe Repair",
        customer_id="cust-003",
        customer_name="Sunset Senior Living",
        type=JobType.plumbing,
        status=JobStatus.completed,
        technician_id="tech-001",
        technician_name="Carlos Mendez",
        address="3200 Judah St, San Francisco, CA 94122",
        description="Emergency repair of burst water main in basement level. Water damage mitigation required.",
        scheduled_date=date(2026, 3, 14),
        completed_date=date(2026, 3, 15),
        estimated_cost=4200.00,
        actual_cost=5800.00,
        notes="Emergency rate applied, after-hours call",
    ),
    Job(
        id="job-003",
        title="Electrical Panel Upgrade",
        customer_id="cust-005",
        customer_name="SF Unified School District",
        type=JobType.electrical,
        status=JobStatus.invoiced,
        technician_id="tech-003",
        technician_name="James O'Brien",
        address="1000 Portola Dr, San Francisco, CA 94127",
        description="Upgrade 200A to 400A electrical panel at Lincoln High School. Code compliance upgrade.",
        scheduled_date=date(2026, 3, 1),
        completed_date=date(2026, 3, 8),
        estimated_cost=12500.00,
        actual_cost=11800.00,
        notes="Completed ahead of schedule",
    ),
    Job(
        id="job-004",
        title="Water Heater Replacement x6",
        customer_id="cust-004",
        customer_name="Pacific Heights Condos",
        type=JobType.plumbing,
        status=JobStatus.scheduled,
        technician_id="tech-001",
        technician_name="Carlos Mendez",
        address="2400 Broadway, San Francisco, CA 94115",
        description="Replace 6 aging water heaters in units 12, 15, 22, 28, 35, 41 with high-efficiency tankless units.",
        scheduled_date=date(2026, 3, 28),
        estimated_cost=18000.00,
        notes="HOA approved, access coordinated with residents",
    ),
    Job(
        id="job-005",
        title="HVAC Preventive Maintenance Q1",
        customer_id="cust-007",
        customer_name="Oakland Children's Hospital",
        type=JobType.hvac,
        status=JobStatus.completed,
        technician_id="tech-002",
        technician_name="Sarah Chen",
        address="747 52nd St, Oakland, CA 94609",
        description="Quarterly HVAC maintenance: filter replacement, coil cleaning, refrigerant check on all 12 rooftop units.",
        scheduled_date=date(2026, 3, 22),
        completed_date=date(2026, 3, 25),
        estimated_cost=8500.00,
        actual_cost=8500.00,
        notes="All units within spec, minor belt replacement on RTU-7",
    ),
    Job(
        id="job-006",
        title="Showroom Lighting Retrofit",
        customer_id="cust-006",
        customer_name="Fremont Auto Mall",
        type=JobType.electrical,
        status=JobStatus.in_progress,
        technician_id="tech-003",
        technician_name="James O'Brien",
        address="5700 Auto Mall Pkwy, Fremont, CA 94538",
        description="LED lighting retrofit for Honda and Toyota showrooms. 240 fixtures total.",
        scheduled_date=date(2026, 3, 20),
        estimated_cost=32000.00,
        notes="Working after-hours to minimize disruption",
    ),
    Job(
        id="job-007",
        title="Kitchen Plumbing Renovation",
        customer_id="cust-001",
        customer_name="Bay Area Homes LLC",
        type=JobType.plumbing,
        status=JobStatus.completed,
        technician_id="tech-004",
        technician_name="Maria Santos",
        address="1450 Market St, Unit 4B, San Francisco, CA 94102",
        description="Complete kitchen plumbing renovation including new supply lines, drain relocation, and dishwasher hookup.",
        scheduled_date=date(2026, 3, 10),
        completed_date=date(2026, 3, 12),
        estimated_cost=3800.00,
        actual_cost=4100.00,
        notes="Minor additional work for code compliance",
    ),
    Job(
        id="job-008",
        title="Convention Center Chiller Service",
        customer_id="cust-008",
        customer_name="San Jose Convention Center",
        type=JobType.hvac,
        status=JobStatus.scheduled,
        technician_id="tech-005",
        technician_name="David Park",
        address="150 W San Carlos St, San Jose, CA 95113",
        description="Annual chiller inspection and service for 500-ton centrifugal chiller. Oil analysis, tube inspection, controls calibration.",
        scheduled_date=date(2026, 4, 1),
        estimated_cost=15000.00,
        notes="Must be completed before summer season",
    ),
    Job(
        id="job-009",
        title="Bathroom Remodel Plumbing",
        customer_id="cust-001",
        customer_name="Bay Area Homes LLC",
        type=JobType.plumbing,
        status=JobStatus.invoiced,
        technician_id="tech-001",
        technician_name="Carlos Mendez",
        address="1450 Market St, Unit 7A, San Francisco, CA 94102",
        description="Master bathroom remodel plumbing: dual vanity, freestanding tub, walk-in shower with body jets.",
        scheduled_date=date(2026, 2, 15),
        completed_date=date(2026, 2, 22),
        estimated_cost=7500.00,
        actual_cost=7200.00,
    ),
    Job(
        id="job-010",
        title="Emergency Generator Wiring",
        customer_id="cust-007",
        customer_name="Oakland Children's Hospital",
        type=JobType.electrical,
        status=JobStatus.in_progress,
        technician_id="tech-005",
        technician_name="David Park",
        address="747 52nd St, Oakland, CA 94609",
        description="Install transfer switch and wiring for new 500kW emergency generator. Critical facility upgrade.",
        scheduled_date=date(2026, 3, 24),
        estimated_cost=28000.00,
        notes="Must maintain existing backup during installation",
    ),
    Job(
        id="job-011",
        title="Classroom HVAC Repair",
        customer_id="cust-005",
        customer_name="SF Unified School District",
        type=JobType.hvac,
        status=JobStatus.completed,
        technician_id="tech-004",
        technician_name="Maria Santos",
        address="1220 Noriega St, San Francisco, CA 94122",
        description="Repair failed compressor on rooftop unit serving 8 classrooms at Sunset Elementary.",
        scheduled_date=date(2026, 3, 5),
        completed_date=date(2026, 3, 6),
        estimated_cost=3500.00,
        actual_cost=4200.00,
        notes="Required crane for rooftop access",
    ),
    Job(
        id="job-012",
        title="Fire Alarm System Upgrade",
        customer_id="cust-003",
        customer_name="Sunset Senior Living",
        type=JobType.electrical,
        status=JobStatus.scheduled,
        technician_id="tech-003",
        technician_name="James O'Brien",
        address="3200 Judah St, San Francisco, CA 94122",
        description="Upgrade fire alarm system to addressable type. 85 devices, new panel, and monitoring connection.",
        scheduled_date=date(2026, 4, 5),
        estimated_cost=22000.00,
        notes="Permit pending, coordinate with fire marshal",
    ),
    Job(
        id="job-013",
        title="Parking Garage Ventilation",
        customer_id="cust-008",
        customer_name="San Jose Convention Center",
        type=JobType.hvac,
        status=JobStatus.invoiced,
        technician_id="tech-002",
        technician_name="Sarah Chen",
        address="150 W San Carlos St, San Jose, CA 95113",
        description="Install CO monitoring and ventilation controls for underground parking garage. 4 exhaust fans, 8 CO sensors.",
        scheduled_date=date(2026, 2, 10),
        completed_date=date(2026, 2, 20),
        estimated_cost=19000.00,
        actual_cost=18500.00,
    ),
    Job(
        id="job-014",
        title="Sewer Line Replacement",
        customer_id="cust-005",
        customer_name="SF Unified School District",
        type=JobType.plumbing,
        status=JobStatus.in_progress,
        technician_id="tech-004",
        technician_name="Maria Santos",
        address="350 Girard St, San Francisco, CA 94134",
        description="Replace 200ft of deteriorated clay sewer line at Visitacion Valley Middle School with PVC.",
        scheduled_date=date(2026, 3, 22),
        estimated_cost=16000.00,
        notes="Excavation permits in place, 3-day project",
    ),
    Job(
        id="job-015",
        title="Electrical Safety Inspection",
        customer_id="cust-004",
        customer_name="Pacific Heights Condos",
        type=JobType.electrical,
        status=JobStatus.scheduled,
        technician_id="tech-003",
        technician_name="James O'Brien",
        address="2400 Broadway, San Francisco, CA 94115",
        description="Annual electrical safety inspection for all common areas: parking, lobby, gym, pool equipment, elevators.",
        scheduled_date=date(2026, 3, 30),
        estimated_cost=4500.00,
        notes="Coordinate with HOA for access schedule",
    ),
]

# ---- Equipment ----

EQUIPMENT: list[Equipment] = [
    Equipment(
        id="eq-001",
        name="Ford F-250 Service Truck #1",
        type="vehicle",
        health_score=92.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 2, 15),
        next_service=date(2026, 5, 15),
        purchase_date=date(2024, 6, 1),
        value=62000.00,
        assigned_to="Carlos Mendez",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 2, 15), description="Oil change, tire rotation, brake inspection", cost=450.00, technician="Bay Auto Service"),
            MaintenanceRecord(date=date(2025, 11, 10), description="60k mile service, transmission fluid", cost=1200.00, technician="Bay Auto Service"),
        ],
    ),
    Equipment(
        id="eq-002",
        name="Ford Transit Cargo Van #1",
        type="vehicle",
        health_score=78.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 1, 20),
        next_service=date(2026, 4, 20),
        purchase_date=date(2023, 3, 15),
        value=48000.00,
        assigned_to="Sarah Chen",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 1, 20), description="Oil change, filter replacement", cost=380.00, technician="Bay Auto Service"),
            MaintenanceRecord(date=date(2025, 10, 5), description="Brake pad replacement, rotor resurface", cost=890.00, technician="Bay Auto Service"),
        ],
        notes="AC compressor making noise, schedule check",
    ),
    Equipment(
        id="eq-003",
        name="Hilti TE 70-ATC Rotary Hammer",
        type="tool",
        health_score=95.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 3, 1),
        next_service=date(2026, 9, 1),
        purchase_date=date(2025, 1, 10),
        value=2800.00,
        assigned_to="James O'Brien",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 3, 1), description="Brush replacement, chuck service", cost=120.00, technician="In-house"),
        ],
    ),
    Equipment(
        id="eq-004",
        name="RIDGID K-5208 Sectional Drain Machine",
        type="tool",
        health_score=65.0,
        status=EquipmentStatus.needs_service,
        last_service=date(2025, 11, 15),
        next_service=date(2026, 3, 15),
        purchase_date=date(2023, 8, 20),
        value=4500.00,
        assigned_to="Maria Santos",
        maintenance_history=[
            MaintenanceRecord(date=date(2025, 11, 15), description="Cable replacement, motor inspection", cost=650.00, technician="RIDGID Service Center"),
        ],
        notes="Overdue for service, cable showing wear",
    ),
    Equipment(
        id="eq-005",
        name="Carrier 50XC Rooftop Unit (Spare)",
        type="heavy_equipment",
        health_score=88.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 2, 1),
        next_service=date(2026, 8, 1),
        purchase_date=date(2024, 4, 1),
        value=18000.00,
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 2, 1), description="Refrigerant charge, electrical check", cost=350.00, technician="In-house"),
        ],
    ),
    Equipment(
        id="eq-006",
        name="Milwaukee M18 Fuel Combo Kit",
        type="tool",
        health_score=90.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 3, 10),
        next_service=date(2026, 9, 10),
        purchase_date=date(2025, 6, 15),
        value=1200.00,
        assigned_to="David Park",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 3, 10), description="Battery health check, tool calibration", cost=0.00, technician="In-house"),
        ],
    ),
    Equipment(
        id="eq-007",
        name="CAT 303 Mini Excavator",
        type="heavy_equipment",
        health_score=72.0,
        status=EquipmentStatus.operational,
        last_service=date(2025, 12, 20),
        next_service=date(2026, 3, 20),
        purchase_date=date(2022, 9, 1),
        value=85000.00,
        maintenance_history=[
            MaintenanceRecord(date=date(2025, 12, 20), description="500hr service, hydraulic filter, tracks inspection", cost=2200.00, technician="CAT Dealer"),
            MaintenanceRecord(date=date(2025, 6, 15), description="Annual inspection, undercarriage", cost=3500.00, technician="CAT Dealer"),
        ],
        notes="Due for service this week",
    ),
    Equipment(
        id="eq-008",
        name="Fluke 1770 Power Quality Analyzer",
        type="tool",
        health_score=98.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 3, 15),
        next_service=date(2027, 3, 15),
        purchase_date=date(2025, 9, 1),
        value=8500.00,
        assigned_to="James O'Brien",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 3, 15), description="Annual calibration", cost=450.00, technician="Fluke Service"),
        ],
    ),
    Equipment(
        id="eq-009",
        name="Ford F-350 Service Truck #2",
        type="vehicle",
        health_score=45.0,
        status=EquipmentStatus.out_of_service,
        last_service=date(2026, 3, 18),
        next_service=date(2026, 3, 30),
        purchase_date=date(2021, 11, 1),
        value=55000.00,
        assigned_to="",
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 3, 18), description="Engine misfire diagnosis, injector replacement pending", cost=0.00, technician="Bay Auto Service"),
            MaintenanceRecord(date=date(2025, 12, 1), description="Transmission service, coolant flush", cost=1800.00, technician="Bay Auto Service"),
        ],
        notes="In shop for injector replacement, ETA March 30",
    ),
    Equipment(
        id="eq-010",
        name="Navien NPE-240A Tankless Water Heater (Demo)",
        type="heavy_equipment",
        health_score=100.0,
        status=EquipmentStatus.operational,
        last_service=date(2026, 3, 1),
        next_service=date(2027, 3, 1),
        purchase_date=date(2026, 1, 15),
        value=3200.00,
        maintenance_history=[
            MaintenanceRecord(date=date(2026, 3, 1), description="Initial setup and testing", cost=0.00, technician="In-house"),
        ],
        notes="Showroom/demo unit for customer presentations",
    ),
]

# ---- Compliance Items ----

COMPLIANCE_ITEMS: list[ComplianceItem] = [
    ComplianceItem(
        id="comp-001",
        name="California C-36 Plumbing License",
        category="license",
        issued_date=date(2024, 7, 1),
        expiry_date=date(2026, 6, 30),
        status=ComplianceStatus.valid,
        issuing_authority="CSLB",
        reference_number="PLB-2024-88431",
    ),
    ComplianceItem(
        id="comp-002",
        name="California C-20 HVAC License",
        category="license",
        issued_date=date(2024, 7, 1),
        expiry_date=date(2026, 6, 30),
        status=ComplianceStatus.valid,
        issuing_authority="CSLB",
        reference_number="HVAC-2024-77219",
    ),
    ComplianceItem(
        id="comp-003",
        name="California C-10 Electrical License",
        category="license",
        issued_date=date(2024, 7, 1),
        expiry_date=date(2026, 6, 30),
        status=ComplianceStatus.valid,
        issuing_authority="CSLB",
        reference_number="ELEC-2024-66108",
    ),
    ComplianceItem(
        id="comp-004",
        name="General Liability Insurance",
        category="insurance",
        issued_date=date(2025, 9, 1),
        expiry_date=date(2026, 8, 31),
        status=ComplianceStatus.valid,
        issuing_authority="State Farm Commercial",
        reference_number="GL-SF-2025-44201",
        notes="$2M coverage, $5M umbrella",
    ),
    ComplianceItem(
        id="comp-005",
        name="Workers Compensation Insurance",
        category="insurance",
        issued_date=date(2025, 9, 1),
        expiry_date=date(2026, 4, 15),
        status=ComplianceStatus.expiring,
        issuing_authority="Hartford",
        reference_number="WC-HF-2025-33109",
        notes="Renewal quote requested",
    ),
    ComplianceItem(
        id="comp-006",
        name="SF Building Permit - Sunset Senior Living",
        category="permit",
        issued_date=date(2026, 2, 1),
        expiry_date=date(2026, 8, 1),
        status=ComplianceStatus.valid,
        issuing_authority="SF DBI",
        reference_number="BP-2026-0201-4421",
    ),
    ComplianceItem(
        id="comp-007",
        name="EPA 608 Certification - Sarah Chen",
        category="certification",
        issued_date=date(2023, 5, 15),
        expiry_date=date(2026, 5, 14),
        status=ComplianceStatus.expiring,
        issuing_authority="EPA",
        reference_number="EPA608-SC-2023",
        notes="Universal certification, renewal scheduled April",
    ),
    ComplianceItem(
        id="comp-008",
        name="Commercial Vehicle Insurance",
        category="insurance",
        issued_date=date(2025, 6, 1),
        expiry_date=date(2026, 5, 31),
        status=ComplianceStatus.valid,
        issuing_authority="Progressive Commercial",
        reference_number="CV-PC-2025-88712",
        notes="Covers all 3 fleet vehicles",
    ),
    ComplianceItem(
        id="comp-009",
        name="Backflow Prevention Tester Cert",
        category="certification",
        issued_date=date(2024, 1, 10),
        expiry_date=date(2026, 1, 9),
        status=ComplianceStatus.expired,
        issuing_authority="AWWA",
        reference_number="BPT-AWWA-2024-001",
        notes="OVERDUE - Carlos Mendez needs renewal",
    ),
    ComplianceItem(
        id="comp-010",
        name="Oakland Business License",
        category="license",
        issued_date=date(2025, 1, 1),
        expiry_date=date(2025, 12, 31),
        status=ComplianceStatus.expired,
        issuing_authority="City of Oakland",
        reference_number="OBL-2025-12345",
        notes="OVERDUE - Renewal application submitted, pending",
    ),
]

# ---- Pricing Rules ----

PRICING_RULES: list[PricingRule] = [
    PricingRule(
        id="price-001",
        name="Plumbing - Standard",
        job_type=JobType.plumbing,
        base_rate=125.00,
        peak_multiplier=1.3,
        emergency_multiplier=1.75,
        weekend_multiplier=1.5,
        seasonal_adjustment=1.0,
        notes="Includes first hour, materials billed separately",
    ),
    PricingRule(
        id="price-002",
        name="HVAC - Standard",
        job_type=JobType.hvac,
        base_rate=145.00,
        peak_multiplier=1.25,
        emergency_multiplier=1.6,
        weekend_multiplier=1.4,
        seasonal_adjustment=1.15,
        notes="Summer seasonal adjustment active Jun-Sep",
    ),
    PricingRule(
        id="price-003",
        name="Electrical - Standard",
        job_type=JobType.electrical,
        base_rate=135.00,
        peak_multiplier=1.2,
        emergency_multiplier=1.65,
        weekend_multiplier=1.35,
        seasonal_adjustment=1.0,
        notes="Master electrician rate, journeyman rate is 80%",
    ),
    PricingRule(
        id="price-004",
        name="General - Standard",
        job_type=JobType.general,
        base_rate=95.00,
        peak_multiplier=1.15,
        emergency_multiplier=1.5,
        weekend_multiplier=1.25,
        seasonal_adjustment=1.0,
        notes="Handyman-level tasks, no specialty license required",
    ),
]

# ---- Revenue Data (last 12 months) ----

REVENUE_DATA: list[RevenueData] = [
    RevenueData(month="Apr 2025", revenue=68200, jobs_completed=22),
    RevenueData(month="May 2025", revenue=74500, jobs_completed=26),
    RevenueData(month="Jun 2025", revenue=82100, jobs_completed=28),
    RevenueData(month="Jul 2025", revenue=91300, jobs_completed=31),
    RevenueData(month="Aug 2025", revenue=88700, jobs_completed=30),
    RevenueData(month="Sep 2025", revenue=79400, jobs_completed=27),
    RevenueData(month="Oct 2025", revenue=72600, jobs_completed=24),
    RevenueData(month="Nov 2025", revenue=65800, jobs_completed=21),
    RevenueData(month="Dec 2025", revenue=58200, jobs_completed=18),
    RevenueData(month="Jan 2026", revenue=63400, jobs_completed=20),
    RevenueData(month="Feb 2026", revenue=71200, jobs_completed=23),
    RevenueData(month="Mar 2026", revenue=85600, jobs_completed=29),
]
